/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes
import { createRoute } from '@tanstack/react-router'
import Convert from '../pages/Convert/Convert.tsx'
import Home from '../pages/Home/Home.tsx'

const home = createRoute({
	path: '/',
	component: Home
})

const convert = createRoute({
	path: '/convert',
	component: Convert
})

export const routeTree = [home, convert]
