/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as WalletIndexImport } from './routes/wallet/index'
import { Route as WalletConvertImport } from './routes/wallet/convert'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WalletIndexRoute = WalletIndexImport.update({
  path: '/wallet/',
  getParentRoute: () => rootRoute,
} as any)

const WalletConvertRoute = WalletConvertImport.update({
  path: '/wallet/convert',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/wallet/convert': {
      id: '/wallet/convert'
      path: '/wallet/convert'
      fullPath: '/wallet/convert'
      preLoaderRoute: typeof WalletConvertImport
      parentRoute: typeof rootRoute
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthRoute,
  WalletConvertRoute,
  WalletIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/wallet/convert",
        "/wallet/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/wallet/convert": {
      "filePath": "wallet/convert.tsx"
    },
    "/wallet/": {
      "filePath": "wallet/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
