/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletImport } from './routes/wallet'
import { Route as PreviewImport } from './routes/preview'
import { Route as ConvertImport } from './routes/convert'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WalletRoute = WalletImport.update({
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any)

const PreviewRoute = PreviewImport.update({
  path: '/preview',
  getParentRoute: () => rootRoute,
} as any)

const ConvertRoute = ConvertImport.update({
  path: '/convert',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertImport
      parentRoute: typeof rootRoute
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ConvertRoute,
  PreviewRoute,
  WalletRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/convert",
        "/preview",
        "/wallet"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/convert": {
      "filePath": "convert.tsx"
    },
    "/preview": {
      "filePath": "preview.tsx"
    },
    "/wallet": {
      "filePath": "wallet.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
